defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  ink-link@*:
    peerDependencies:
      ink: "*"
      react: "*"
  ink-testing-library@*:
    peerDependencies:
      ink: "*"
      react: "*"
